type TitleTemplate = {
	weight: number;
	template: string,
	lists: { [key: string]: string[] };
};

export function getRandomName() {
	const pool = Array.from(Object.entries(titleTemplates)).reduce((p, [key, template]) => {
		p.push(...Array(template.weight).fill(key));
		return p;
	}, [] as string[]);
	const templateKey = pool[Math.floor(Math.random() * pool.length)];
	return hydrateTemplate(titleTemplates[templateKey]);
}

function hydrateTemplate(template: TitleTemplate) {
	const vars = Object.keys(template.lists);
	return vars.reduce((t, v) => {
		const varOptions = template.lists[v];
		const randomOption = varOptions[Math.floor(Math.random() * varOptions.length)];
		return t.replace(`{${v}}`, randomOption);
	}, template.template);
}


const common_adjectives = [
	'Apocalyptic',
	'Atomic',
	'Cataclysmic',
	'Classified',
	'Confidential',
	'Covert',
	'Cunning',
	'Dangerous',
	'Deadly',
	'Double',
	'Fatal',
	'Final',
	'Ghost',
	'Golden',
	'Impossible',
	'International',
	'Lethal',
	'Lost',
	'Menacing',
	'Merciless',
	'Mysterious',
	'Next',
	'Omega',
	'Ominous',
	'Quantum',
	'Red',
	'Rogue',
	'Royal',
	'Ruthless',
	'Secret',
	'Shadow',
	'Sinister',
	'Supreme',
	'Top Secret',
	'Treacherous',
	'Treasonous',
	'Triple',
	'Ultimate'
];


const common_nouns: string[] = [
	"Abyss",
	"Agent",
	"Alliance",
	"Apex",
	"Apparition",
	"Aura",
	"Betrayal",
	"Catalyst",
	"Cell",
	"Chameleon",
	"Chasm",
	"Chimera",
	"Cipher",
	"Circle",
	"Citadel",
	"City",
	"Coalition",
	"Code",
	"Conspiracy",
	"Conundrum",
	"Covenant",
	"Deception",
	"Decree",
	"Defector",
	"Depth",
	"Dilemma",
	"Directive",
	"Dirge",
	"Discovery",
	"Door",
	"Double",
	"Eclipse",
	"Edict",
	"Effect",
	"Enclave",
	"Enigma",
	"Entity",
	"Eyes",
	"Fall",
	"File",
	"Fortress",
	"Gambit",
	"Game",
	"Ghost",
	"Heart",
	"Hub",
	"Hybrid",
	"Ideal",
	"Identity",
	"Illusion",
	"Infiltration",
	"Initiative",
	"Key",
	"Labyrinth",
	"Lament",
	"Legacy",
	"Liability",
	"Lie",
	"Machine",
	"Maelstrom",
	"Mandate",
	"Maneuver",
	"Masquerade",
	"Mass",
	"Maze",
	"Menace",
	"Message",
	"Mirage",
	"Mission",
	"Mole",
	"Monster",
	"Mystery",
	"Net",
	"Network",
	"Nexus",
	"Oblivion",
	"Omen",
	"Operation",
	"Organization",
	"Overture",
	"Pact",
	"Paradigm",
	"Paradox",
	"Paragon",
	"Path",
	"Phantom",
	"Plot",
	"Ploy",
	"Point",
	"Predator",
	"Presence",
	"Prophecy",
	"Protocol",
	"Puppet",
	"Puzzle",
	"Reckoning",
	"Refuge",
	"Report",
	"Requiem",
	"Revelation",
	"Rift",
	"Ruse",
	"Saboteur",
	"Sanction",
	"Scheme",
	"Secret",
	"Shade",
	"Shadow",
	"Shadows",
	"Signal",
	"Snare",
	"Spark",
	"Spectacle",
	"Spectre",
	"Spiral",
	"Spy",
	"State",
	"Storm",
	"Stratagem",
	"Stronghold",
	"Summit",
	"Supremacy",
	"Swirl",
	"Syndicate",
	"Target",
	"Theory",
	"Threat",
	"Traitor",
	"Trap",
	"Tunnel",
	"Turbulence",
	"Turn",
	"Twist",
	"Ultimacy",
	"Ultimatum",
	"Umbra",
	"Void",
	"Vortex",
];


// const nouns_that_can_be_adjectives: string[] = [
// 	'Agent',
// 	'Aura',
// 	'Betrayal',
// 	'Catalyst',
// 	'Chasm',
// 	'Chimera',
// 	'Ghost',
// 	'Illusion',
// 	'Legacy',
// 	'Liability',
// 	'Line',
// 	'Machine',
// 	'Maelstrom',
// 	'Maneuver',
// 	'Masquerade',
// 	'Mandate',
// 	'Menace',
// 	'Message',
// 	'Mirage',
// 	'Mission',
// 	'Net',
// 	'Network',
// 	'Nexus',
// 	'Oblivion',
// 	'Omen',
// 	'Operation',
// 	'Organization',
// 	'Overture',
// 	'Pact',
// 	'Paradigm',
// 	'Paradox',
// 	'Phantom',
// 	'Plot',
// 	'Point',
// 	'Ploy',
// 	'Presence',
// 	'Prelude',
// 	'Prologue',
// 	'Prophecy',
// 	'Protocol',
// 	'Reckoning',
// 	'Requiem',
// 	'Report',
// 	'Revelation',
// 	'Rift',
// 	'Rising',
// 	'Ruse',
// 	'Sanction',
// 	'Scheme',
// 	'Secret',
// 	'Shadow',
// 	'Shadows',
// 	'Signal',
// 	'Snare',
// 	'Spectacle',
// 	'Specter',
// 	'State',
// 	'Stratagem',
// 	'Supremacy',
// 	'Syndicate',
// 	'Target',
// 	'Threat',
// 	'Trap',
// 	'Turn',
// 	'Twist',
// 	'Ultimacy',
// 	'Ultimatum',
// 	'Void',
// 	'Vortex',
// 	'Web',
// ];

const thingsToBeInOrOf: string[] = [
	'Beijing',
	'Berlin',
	'London',
	'Moscow',
	'New York',
	'Our Midst',
	'Paris',
	'Prague',
	'Rome',
	'the Attic',
	'the CIA',
	'the Dark',
	'the Desert',
	'the FBI',
	'the Fog',
	'the House',
	'the Kremlin',
	'the Light',
	'the Mirror',
	'the Night',
	'the Pentagon',
	'the Shadows',
	'the Sun',
	'the System',
	'the Underworld',
	'Tokyo',
	'Vienna',
	'Washington',
	'Machine',
	'Shadows',
	"Love"
];





const titleTemplates: Record<string, TitleTemplate> = {
	adjectiveNoun: {
		weight: 4,
		template: '{the}{adj} {noun}',
		lists: {
			adj: common_adjectives,
			noun: common_nouns,
			the: ['The ', '']
		}
	},
	nounInThing: {
		weight: 2,
		template: '{the}{noun} {inOf} {thing}',
		lists: {
			noun: common_nouns,
			thing: thingsToBeInOrOf,
			the: ['The ', ''],
			inOf: ['in', 'of']
		}
	},
	mission: {
		weight: 1,
		template: 'Mission: {word}',
		lists: {
			word: [
				"Inconvenient",
				"Unlikely",
				"Implausible",
				"Incomplete",
				"Improbable",
				"Inept",
				"Unachievable",
				"Unrealistic",
				"Unnecessary",
				"Unrealized",
				"Unskilled",
				"Unhinged",
			],
		}
	},
	bourne: {
		weight: 1,
		template: 'Bourne: {word}',
		lists: {
			word: [
				"Insecurity",
				"Indecision",
				"Incompetence",
				"Irrelevance",
				"Ignorance",
				"Inconsistency",
				"Invisibility",
				"Indifference",
				"Illegibility",
				"Unemployed",
				"Uninsured",
				"Uncoordinated",
				"Uninvited",
				"Unimpressed",
				"Unprepared",
				"Unsettled",
				"Unfocused",
				"Underwhelmed",
				"Unmotivated",
				"Mediocrity",
				"Inferiority",
				"Adequacy",
			],
		}
	}
};

